platform:ios, '8.0'
inhibit_all_warnings!


target 'ProjectBase' do
    pod 'Masonry', '~> 1.0.1'
    pod 'MJRefresh', '~> 3.1.1'
    pod 'MJExtension', '~> 3.0.10'
    pod 'AFNetworking', '~> 3.1.0'
    pod 'EGOCache', '~> 2.1.3'
    pod 'SDWebImage', '~> 3.8.1'
    pod 'UMengSocialCOM', '~> 5.2.1'
    pod 'GVUserDefaults', '~> 1.0.2'
    pod 'JazzHands', '~> 2.0.8'
    pod 'SMPageControl', '~> 1.2'
    pod 'NYXImagesKit', '~> 2.3'
    pod 'SDCycleScrollView', '~> 1.65'
end
